#!/bin/csh
cd /users/yjzhang/thesis/CSP/qcsp-alex/
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-24.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-24.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-27.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-27.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-30.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-30.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-33.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-33.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-36.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-36.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-39.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-39.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-42.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-42.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-45.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-45.msg
 
 
 

