#!/bin/csh
cd /users/yjzhang/thesis/CSP/qcsp-alex/
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-1.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-1.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-3.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-3.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-6.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-6.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-9.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-9.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-12.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-12.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-15.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-15.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-18.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-18.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-21.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-21.msg
 
 
 

#!/bin/csh
cd /users/yjzhang/thesis/CSP/qcsp-alex/
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-24.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-24.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-27.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-27.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-30.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-30.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-33.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-33.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-36.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-36.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-39.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-39.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-42.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-42.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-45.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-45.msg
 
 
 

#!/bin/csh
cd /users/yjzhang/thesis/CSP/qcsp-alex/
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-48.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-48.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-51.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-51.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-54.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-54.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-66.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-66.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-78.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-78.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-90.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-90.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-102.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-102.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-114.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-114.msg
 
 
 

