#!/bin/csh
cd /users/yjzhang/thesis/CSP/qcsp-alex/
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-1.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/1.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-2.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/2.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-3.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/3.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-4.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/4.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-5.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/5.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-6.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/6.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-7.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/7.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-8.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/8.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-9.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/9.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-10.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-11.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/11.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-12.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/12.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-13.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/13.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-14.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/14.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-15.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/15.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-16.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/16.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-17.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/17.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-18.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/18.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-19.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/19.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-20.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/20.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-21.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/21.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-22.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/22.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-23.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/23.msg
 
 

