#!/bin/csh
cd /users/yjzhang/thesis/CSP/qcsp-alex/
 

 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-3-batch-36.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/3-36.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-3-batch-39.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/3-39.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-3-batch-42.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/3-42.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-3-batch-45.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/3-45.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-3-batch-48.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/3-48.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-3-batch-51.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/3-51.msg
 
 

 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-3-batch-54.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/3-54.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-3-batch-66.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/3-66.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-3-batch-78.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/3-78.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-3-batch-90.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/3-90.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-3-batch-102.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/3-102.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-3-batch-114.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/3-114.msg
 
 
 
 

