@ 2test.c
@ /usr/local/lib/gcc-lib/sparc-sun-solaris2.5/2.7.2/include/stdio.h
@ /usr/local/lib/gcc-lib/sparc-sun-solaris2.5/2.7.2/include/stdio.h
@ /usr/include/sys/feature_tests.h
@ /usr/include/sys/feature_tests.h
@ /usr/local/lib/gcc-lib/sparc-sun-solaris2.5/2.7.2/include/stdio.h
	__iob
	__iob._cnt
	__iob._ptr
	__iob._base
	__iob._flag
	__iob._file
	_lastbuf
	_bufendtab
	_sibuf
	_sobuf
@ /usr/local/lib/gcc-lib/sparc-sun-solaris2.5/2.7.2/include/stdio.h
	optarg
	optind
	opterr
	optopt
@ /usr/local/lib/gcc-lib/sparc-sun-solaris2.5/2.7.2/include/stdio.h
@ /usr/local/lib/gcc-lib/sparc-sun-solaris2.5/2.7.2/include/stdio.h
@ 2test.c
@ 2func1.h
@ 2test.c
