graph: {
	hidden: 2 
	node: { title: "nil"
		label: "invisible node"
		level: 0
		info1: "guarantees graph has one node and edge"
		info2: "so that xvcg does not core dump"
		info3: "since edge is hidden there is no effect"
	}
	edge: {sourcename: "nil" targetname: "nil"  class: 2 }
	textmode  : center
	node: { title: "14"
		label:"main:i
size: 10
equiv: 1"
		level: 1
		borderwidth: 4
		info1:"14"
		info2:"20"
		info3:"2test.c"
	}
	node: { title: "15"
		label:"main:j
size: 4
equiv: 1"
		level: 0
		borderwidth: 4
shape: ellipse
		info1:"15"
		info2:"20"
		info3:"2test.c"
	}
}
