globals 14 procs 3 addrs 0 chains 0 headers 1 files 2
  1    1   16    4 X main
  2    1    4    1 X func1
  3   -1    0    0 X printf

  0   3    16   20    211 2test.
  1   1     4    5     41 2func1.
14 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5/2.7.2/include/stdio.h
	 14 optopt
	 13 opterr
	 12 optind
	 11 optarg
	 10 _sobuf
	  9 _sibuf
	  8 _bufendtab
	  7 _lastbuf
	  6 __iob._file
	  5 __iob._flag
	  4 __iob._base
	  3 __iob._ptr
	  2 __iob._cnt
	  1 __iob
