/* This program generated by adt-translate.lisp */ 
/* Datafile = ADT-Situation/Sit-nil-nil-nil-97 */

#include <stdio.h>

#define DEFAULT_SIZE 99    /* define array size */

main () {

/* Initial variable declarations */
int firstint;
firstint = 0;
int null;
null = 0;
int firstbool;
firstbool = 0;
float firstreal;
firstreal = 0.0;
char firstchar;
firstchar = 0;

/* Initial array declarations */
int firstarrayi[DEFAULT_SIZE];
char firstarrayc[DEFAULT_SIZE];
float firstarrayr[DEFAULT_SIZE];
int firstarrayb[DEFAULT_SIZE];

/* Initial inline function protoypes */
int   checkIntInt    (int   x);
int   checkIntBool   (int   x);
int   checkIntChar   (char  x);
int   checkIntReal   (float x);
float checkRealInt   (int   x);
float checkRealBool  (int   x);
float checkRealChar  (char  x);
float checkRealReal  (float x);
int   checkBoolInt   (int   x);
int   checkBoolBool  (int   x);
int   checkBoolChar  (char  x);
int   checkBoolReal  (float x);
char  checkCharInt   (int   x);
char  checkCharBool  (int   x);
char  checkCharChar  (char  x);
char  checkCharReal  (float x);

/* Code parsing commenced ... here. */

/* ........... adtq1_a 0 100  decl array a char 99   ........... */
char a[99];
/* ........... adtq1_b 1 200  zero idx   ........... */
int idx;
idx = 0;
idx = 0;
/* ........... adtq1_c 2 300  while result   ........... */
int result;
result = 0;
while( result != 0 )
/* ........... adtq1_d 3 310  begin block1   ........... */
{   /* begin block block1 */
/* ........... adtq1_g 4 400  assign a idx elemb   ........... */
char elemb;
elemb = 0;
elemb = a[idx];
/* ........... adtq1_i 5 500  increment idx   ........... */
 ++idx;
/* ........... adtq1_e 6 600  end block1   ........... */
}   /* end block block1 */
/* ........... adtq1_f 7 700  assign a idx elem   ........... */
char elem;
elem = 0;
elem = a[idx];
/* ........... adtq1_h 8 800  not_equals elem null result   ........... */
result = !(elem == null);

}  /* end of C program */


