#
CC = CC 
CFLAGS = -F -Qpath /users1/grad/yjzhang/Gen++ 
#TARGET = myscanf.zyj
#.SUFFIXES: 
.SUFFIXES: .C.o.

CSOURCE = alg.C
OBJS = alg.o

all:  $(OBJS) 

alg.o:	alg.C 
	$(CC) $(CFLAGS) alg.C  




