#!/bin/csh
cd /users/yjzhang/thesis/CSP/qcsp-alex/
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-23.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-23.msg
 
 
 

