#!/bin/csh
cd /users/yjzhang/thesis/CSP/qcsp-alex/
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-7.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/7.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-17.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/17.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-19.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/19.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-20.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/20.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-21.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/21.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-22.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/22.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-exe-23.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/23.msg
 
 

