#!/bin/csh
cd /users/yjzhang/thesis/CSP/qcsp-alex/
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-48.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-48.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-51.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-51.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-54.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-54.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-66.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-66.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-78.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-78.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-90.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-90.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-102.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-102.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-114.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-114.msg
 
 
 

