#!/bin/csh
cd /users/yjzhang/thesis/CSP/qcsp-alex/
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-16.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-16.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-17.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-17.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-18.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-18.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-19.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-19.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-20.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-20.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-21.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-21.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-22.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-22.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/exp-10-batch-23.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/10-23.msg
 
 
 

