#!/bin/csh
cd /users/yjzhang/thesis/CSP/qcsp-alex/

\cp exp-2-data.lisp this-exp-data.lisp
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-0.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/0.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-1.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/1.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-2.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/2.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-3.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/3.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-4.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/4.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-5.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/5.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-6.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/6.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-7.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/7.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-8.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/8.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-9.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/9.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-10.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/10.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-11.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/11.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-12.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/12.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-13.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/13.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-14.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/14.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-15.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/15.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-16.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/16.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-17.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/17.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-18.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/18.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-19.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/19.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-20.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/20.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-21.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/21.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-22.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/22.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-23.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/23.msg

mkdir /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/bexp-2
\cp   /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/* \
     /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/bexp-2
 
\cp exp-ssa-data.lisp this-exp-data.lisp
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-0.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/0.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-1.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/1.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-2.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/2.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-3.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/3.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-4.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/4.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-5.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/5.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-6.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/6.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-7.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/7.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-8.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/8.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-9.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/9.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-10.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/10.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-11.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/11.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-12.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/12.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-13.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/13.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-14.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/14.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-15.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/15.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-16.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/16.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-17.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/17.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-18.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/18.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-19.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/19.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-20.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/20.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-21.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/21.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-22.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/22.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-23.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/23.msg
 
mkdir /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/bexp-ssa 
\cp   /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/* \
     /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/bexp-ssa 

 
\cp exp-10-data.lisp this-exp-data.lisp
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-0.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/0.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-1.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/1.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-2.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/2.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-3.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/3.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-4.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/4.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-5.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/5.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-6.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/6.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-7.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/7.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-8.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/8.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-9.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/9.msg
 
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-10.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/10.msg
 
nice time /extra/acl4.2/bin/cl <\
		/users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-11.lisp >\
		/users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/11.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-12.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/12.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-13.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/13.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-14.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/14.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-15.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/15.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-16.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/16.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-17.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/17.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-18.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/18.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-19.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/19.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-20.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/20.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-21.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/21.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-22.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/22.msg
 
nice time /extra/acl4.2/bin/cl <\
        /users/yjzhang/thesis/CSP/qcsp-alex/MyBatch/batch-23.lisp >\
        /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/23.msg
 
mkdir /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/bexp-10
\cp   /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/Inter/* \
     /users/yjzhang/thesis/CSP/qcsp-alex/testdata/Results/bexp-10

 
 
 

