(defun test ( inlist )
	(cond ((endp inlist) nil)
			(T (cond ((endp (rest inlist)) T)
					 (T nil )) 
				(print (first inlist)) (print (second inlist)))))

(defun test1 ( ) 
(combine-two-assoc-list '(((10)) ((WHILEC_R_4) . WHILEC_11) ((WHILEC_R_3) . WHILEC_8)
 ((WHILEC_R_2) . WHILEC_7) ((WHILEC_R_1) . WHILEC_6) ((19))
 ((K WHILEC 3) . WHILEC_4) ((I WHILEC 3) . WHILEC_9) ((2))
 ((J WHILEC 3) . WHILEC_2)) 
'(((10)) ((WHILEC_R_4)) ((WHILEC_R_3)) ((WHILEC_R_2)) ((WHILEC_R_1)) ((19))
 ((K WHILEC 3) . WHILEC_4) ((I WHILEC 3) . WHILEC_3) ((2))
 ((J WHILEC 3) . WHILEC_2)) 
))
(defun test2()
(modify-var-assoc-list 'WHILEC_11 '((I WHILEC 3)) 
'(((WHILEC_R_4) . WHILEC_10) ((WHILEC_R_3) . WHILEC_9) ((10))
 ((WHILEC_R_2) . WHILEC_8) ((WHILEC_R_1) . WHILEC_6) ((20))
 ((K WHILEC 3) . WHILEC_4) ((I WHILEC 3) WHILEC_11 WHILEC_3) ((2))
 ((J WHILEC 3) . WHILEC_2))))  
 
