(in-package #:phd-qcsp-may29)
;; comment.lisp

(defun load-comment ()
  (load "comment.lisp"))

(defun comment (com )
  (if (not (eq t nil))
      (let ()
	(format t	"~&> ~A " com)
	)) )

(defun comment1 (com &optional (var nil))
  (if (not (eq t nil))
      (let ()
	(format t	"~&> ~A " com)
	(format t " < ~A > ~&" var)
	)) )

(defun comment2 (com &optional (var nil) (var2 nil))
  (if (not (eq t nil))
      (let ()
	(format t	"~&> ~A " com)
	(format t " < ~A," var)
	(format t " ~A > ~&" var2)
	)) )

(defun comment3 (com &optional (var nil) (var2 nil) (var3 nil) )
  (if (not (eq t nil))
      (let ()
	(format t	"~&> ~A " com)
	(format t " < ~A," var)
	(format t " ~A," var2)
	(format t " ~A > ~&" var3)
	)) )

(defun comment4 (com &optional (var nil) (var2 nil) (var3 nil) (var4 nil))
  (if (not (eq t nil))
      (let ()
	(format t "~2&> ~A " com)
	(format t " < ~A," var)
	(format t " ~A," var2)
	(format t " ~A," var3)
	(format t " ~A > ~&" var4)
	)) )

(defun comment5 (com &optional (var nil) (var2 nil) (var3 nil) (var4 nil)
		    (var5 nil) )
  (if (not (eq t nil))
      (let ()
	(format t "~2&> ~A " com)
	(format t " < ~A," var)
	(format t " ~A," var2)
	(format t " ~A," var3)
	(format t " ~A," var4)
	(format t " ~A > ~&" var5)
	)) )


