

/*=================================================================*/
/* This product produced by laurae on Mon Sep 25 15:03:29 1995 from file  */
/*    /home3/bloom1/laurae/rb/gc/test.spec using   */
/* the genii applications generator, version Unknown version    */
/*=================================================================*/
/*************************************************************************/
/*************************************************************************/
/** This file Generated by genii- This defines all the types   ***********/
/** of GNODES                                                            */
/** that are needed.                                                     */
/** Generated At; Mon Sep 25 15:03:29 1995, By: laurae                 */
/*************************************************************************/
/*************************************************************************/



#include <strings.h>
#include <stdio.h>

#if __cplusplus
#include <stdlib.h>
#endif

/***   Cin HEADER FILES HERE ***/
#ifdef FUNCTABLE
#include	"ExtFEhdr.h"
#endif

#include "gtypedefs.h"
#include "gnode.h"
#include "print.h"
#include "functable.h"







#if __STDC__ || __cplusplus || c_plusplus
/* #if __cplusplus || c_plusplus */
/* extern "C" { */
/* #endif  */
extern char *mymalloc(int);
extern char *mystrconcat(char *,char *);
extern GNODE gmalloc ();
extern void gfree (GNODE);
extern char *myitoa(long);
/* #if __cplusplus || c_plusplus */
/* }    */
/* #endif */
#else
extern char *mymalloc();
extern char *mystrconcat();
extern GNODE gmalloc ();
extern void gfree();
extern char *myitoa();
#endif


/* First the Enum */
/******************/  

typedef enum {
	Catch = 254 ,
	Label = 253 ,
	Default = 252 ,
	Case = 251 ,
	Try = 250 ,
	Goto = 249 ,
	LabelStmt = 248 ,
	Continue = 247 ,
	Break = 246 ,
	Switch = 245 ,
	Do = 244 ,
	For = 243 ,
	While = 242 ,
	If = 241 ,
	Return = 240 ,
	NullStmt = 239 ,
	ExprStmt = 238 ,
	AsmStmt = 237 ,
	NK_Type = 236 ,
	NK_Enumerator = 235 ,
	NK_Label = 234 ,
	NK_This = 233 ,
	NK_Simple = 232 ,
	NK_Constructor = 231 ,
	NK_Destructor = 230 ,
	NK_Operator = 229 ,
	PMFValue = 228 ,
	AggrValue = 227 ,
	Assign = 226 ,
	RshiftAssign = 225 ,
	LshiftAssign = 224 ,
	MinusAssign = 223 ,
	PlusAssign = 222 ,
	ModAssign = 221 ,
	MultAssign = 220 ,
	DivAssign = 219 ,
	OrAssign = 218 ,
	AndAssign = 217 ,
	XorAssign = 216 ,
	FloatConst = 215 ,
	CharConst = 214 ,
	IntConst = 213 ,
	StringConst = 212 ,
	Literal = 211 ,
	P2MData = 210 ,
	P2MFunction = 209 ,
	Arrow = 208 ,
	Dot = 207 ,
	GeneratedCast = 206 ,
	UserCast = 205 ,
	GConversion = 204 ,
	GDestruction = 203 ,
	GConstruction = 202 ,
	GOperatorCall = 201 ,
	GeneratedCall = 200 ,
	UserCall = 199 ,
	PostInc = 198 ,
	PostDec = 197 ,
	PreDec = 196 ,
	PreInc = 195 ,
	Deref = 194 ,
	AddrOf = 193 ,
	Uplus = 192 ,
	Uminus = 191 ,
	UnaryCount = 190 ,
	Complement = 189 ,
	Not = 188 ,
	Plus = 187 ,
	Minus = 186 ,
	Mult = 185 ,
	Div = 184 ,
	Mod = 183 ,
	Assignment = 182 ,
	NotEq = 181 ,
	EqEq = 180 ,
	LessEq = 179 ,
	Less = 178 ,
	GreaterEq = 177 ,
	Greater = 176 ,
	Lshift = 175 ,
	Rshift = 174 ,
	Comma = 173 ,
	BitOr = 172 ,
	BitAnd = 171 ,
	Xor = 170 ,
	LogOr = 169 ,
	LogAnd = 168 ,
	PrimaryExpr = 167 ,
	Delete = 166 ,
	New = 165 ,
	Mdot = 164 ,
	P2MemberRef = 163 ,
	MemberRef = 162 ,
	Question = 161 ,
	Ccast = 160 ,
	Sizeof_T = 159 ,
	Sizeof_E = 158 ,
	Index = 157 ,
	FunCall = 156 ,
	UnaryExpr = 155 ,
	BinaryExpr = 154 ,
	NullExpr = 153 ,
	StaticInitializer = 152 ,
	TA_Long = 151 ,
	TA_Unsigned = 150 ,
	TA_Signed = 149 ,
	TA_Numeric = 148 ,
	TA_Integral = 147 ,
	TA_Volatile = 146 ,
	TA_Const = 145 ,
	T_Void = 144 ,
	T_LDouble = 143 ,
	T_Double = 142 ,
	T_Float = 141 ,
	T_Long = 140 ,
	T_Int = 139 ,
	T_Short = 138 ,
	T_Char = 137 ,
	T_Zero = 136 ,
	T_Any = 135 ,
	ClassType = 134 ,
	AnonType = 133 ,
	UnionType = 132 ,
	Typeref = 131 ,
	AggrType = 130 ,
	EnumType = 129 ,
	Linkage_Cplusplus = 128 ,
	Linkage_C = 127 ,
	T_Attr = 126 ,
	BuiltinType = 125 ,
	PtrType = 124 ,
	RefType = 123 ,
	ArrayType = 122 ,
	NamedType = 121 ,
	FunctionType = 120 ,
	Overload = 119 ,
	FieldType = 118 ,
	CA_HasOpDelete = 117 ,
	CA_HasOpNew = 116 ,
	CA_HasVirtuals = 115 ,
	CA_HasOpAssign = 114 ,
	CA_HasNullCtor = 113 ,
	CA_HasCopyCtor = 112 ,
	CA_HasDtor = 111 ,
	CA_HasCtor = 110 ,
	CA_Specialized = 109 ,
	CA_Instantiated = 108 ,
	CA_Abstract = 107 ,
	FTA_Ellipsis = 106 ,
	FTA_Static = 105 ,
	FTA_Const = 104 ,
	FunctionTypeAttr = 103 ,
	FA_IncompleteInstantiation = 102 ,
	FA_Instantiation = 101 ,
	FA_Template = 100 ,
	FA_Ellipsis = 99 ,
	FA_Static = 98 ,
	FA_Const = 97 ,
	FA_Virtual = 96 ,
	FA_Inline = 95 ,
	Volatile = 94 ,
	Const = 93 ,
	CV_Spec = 92 ,
	Initializer = 91 ,
	ObjectDecl = 90 ,
	ObjectDef = 89 ,
	Block = 88 ,
	MemInit = 87 ,
	FunctionAttr = 86 ,
	FunctionLinkage = 85 ,
	FunctionDef = 84 ,
	FunctionDecl = 83 ,
	EnumeratorSpec = 82 ,
	BA_Promoted = 81 ,
	BA_Allocated = 80 ,
	BA_Virtual = 79 ,
	BA_Plain = 78 ,
	BA_Private = 77 ,
	BA_Protected = 76 ,
	BA_Public = 75 ,
	BaseAllocation = 74 ,
	BaseAccess = 73 ,
	FriendFunction = 72 ,
	FriendClass = 71 ,
	FriendDeclaration = 70 ,
	MemberDeclaration = 69 ,
	NestedDeclaration = 68 ,
	VisibilitySpec = 67 ,
	AccessSpec = 66 ,
	MemberSpec = 65 ,
	BaseSpec = 64 ,
	ClassAttr = 63 ,
	AnonUnion = 62 ,
	UnionDef = 61 ,
	ClassDef = 60 ,
	UnionDecl = 59 ,
	ClassDecl = 58 ,
	AggrDecl = 57 ,
	AggrDef = 56 ,
	Expression = 55 ,
	ExprActual = 54 ,
	TypeActual = 53 ,
	Actual = 52 ,
	ValueParameter = 51 ,
	TypeParameter = 50 ,
	Parameter = 49 ,
	ClassTemplate = 48 ,
	FunctionTemplate = 47 ,
	DataTemplate = 46 ,
	ObjectSpec = 45 ,
	FunctionSpec = 44 ,
	AsmSpec = 43 ,
	EnumSpec = 42 ,
	AggrSpec = 41 ,
	Typedef = 40 ,
	Template = 39 ,
	LabelSpec = 38 ,
	BogusDecl = 37 ,
	SC_Static = 36 ,
	SC_Member = 35 ,
	SC_Auto = 34 ,
	SC_Register = 33 ,
	SC_Enum = 32 ,
	Scope_Private = 31 ,
	Scope_Protected = 30 ,
	Scope_Public = 29 ,
	Scope_Extern = 28 ,
	Scope_Static = 27 ,
	Scope_Label = 26 ,
	Scope_Local = 25 ,
	Scope_Argument = 24 ,
	Scope_Member = 23 ,
	Scope_Weird = 22 ,
	Statement = 21 ,
	NameValue = 20 ,
	StorageClass = 19 ,
	Type = 18 ,
	TypeName = 17 ,
	FunctionName = 16 ,
	IdName = 15 ,
	Scope = 14 ,
	NameKind = 13 ,
	AccessedName = 12 ,
	LabelName = 11 ,
	TypedName = 10 ,
	NameRef = 9 ,
	Table = 8 ,
	Declaration = 7 ,
	FileSpec = 6 ,
	Location = 5 ,
	CFile = 4 ,
	C_String = 3 ,
	C_File = 2 ,
	C_Float = 1 ,
	C_Integer = 0 ,

} NODETYPE;

#define TYPECOUNTER 255
#define VALIDTYPE(X) ((X >= 0) && (X <= TYPECOUNTER))
#define _G_ROOTTYPE  CFile

#define _G_DATA p

#define _G_AUX q

#define _G_ITER it

#define _G_LOCATION   Location
#define  DEFAULT_CAST(X) ((void *) X)
#define THESAME(x,y) (DEFAULT_CAST( x->node_data.l_dv) == DEFAULT_CAST( y->node_data.l_dv))






/* If the following variables not defined above, we make defaults */	

#ifndef _G_DATA
#define _G_DATA _g_data
#endif


#ifndef _G_AUX
#define _G_AUX _g_aux
#endif


#ifndef _G_ITER
#define _G_ITER _g_iter
#endif



#ifndef _G_LIST
#define _G_LIST _g_list
#endif

#ifndef _G_SEARCH
#define _G_SEARCH _g_search
#endif
#define _G_HAS_INITIALIZER 1
#define _G_HAS_FINALIZER 1
