struct streambuf;
struct ostream;
struct ios;
union ios_user_union;
struct istream;
struct iostream;
struct istream_withassign;
struct ostream_withassign;
struct iostream_withassign;
struct Iostream_init;
struct node;
struct List;
(BeginFunctionNamed List)
(Statement : line 7, 'C++/lists.C' :type For)
(Statement : line 8, 'C++/lists.C' :type ExprStmt)
(Statement : line 9, 'C++/lists.C' :type ExprStmt)
(Statement : line 10, 'C++/lists.C' :type ExprStmt)
(EndFunctionNamed C++/lists.C)
(BeginFunctionNamed insert_front)
(Statement : line 16, 'C++/lists.C' :type ExprStmt)
(Statement : line 17, 'C++/lists.C' :type ExprStmt)
(Statement : line 18, 'C++/lists.C' :type ExprStmt)
(Statement : line 19, 'C++/lists.C' :type If)
(Statement : line 20, 'C++/lists.C' :type ExprStmt)
(Statement : line 22, 'C++/lists.C' :type ExprStmt)
(EndFunctionNamed C++/lists.C)
(BeginFunctionNamed insert_rear)
(Statement : line 29, 'C++/lists.C' :type If)
(Statement : line 30, 'C++/lists.C' :type ExprStmt)
(Statement : line 31, 'C++/lists.C' :type Block)
(Statement : line 32, 'C++/lists.C' :type If)
(Statement : line 33, 'C++/lists.C' :type ExprStmt)
(Statement : line 34, 'C++/lists.C' :type Block)
(Statement : line 35, 'C++/lists.C' :type ExprStmt)
(Statement : line 36, 'C++/lists.C' :type ExprStmt)
(Statement : line 37, 'C++/lists.C' :type ExprStmt)
(Statement : line 38, 'C++/lists.C' :type ExprStmt)
(Statement : line 40, 'C++/lists.C' :type ExprStmt)
(EndFunctionNamed C++/lists.C)
(BeginFunctionNamed in_list)
(Statement : line 49, 'C++/lists.C' :type While)
(Statement : line 49, 'C++/lists.C' :type Block)
(Statement : line 50, 'C++/lists.C' :type If)
(Statement : line 51, 'C++/lists.C' :type Return)
(Statement : line 52, 'C++/lists.C' :type ExprStmt)
(Statement : line 53, 'C++/lists.C' :type ExprStmt)
(Statement : line 55, 'C++/lists.C' :type Return)
(EndFunctionNamed C++/lists.C)
(BeginFunctionNamed remove)
(Statement : line 64, 'C++/lists.C' :type If)
(Statement : line 65, 'C++/lists.C' :type Return)
(Statement : line 66, 'C++/lists.C' :type If)
(Statement : line 66, 'C++/lists.C' :type Block)
(Statement : line 67, 'C++/lists.C' :type ExprStmt)
(Statement : line 68, 'C++/lists.C' :type ExprStmt)
(Statement : line 69, 'C++/lists.C' :type ExprStmt)
(Statement : line 70, 'C++/lists.C' :type ExprStmt)
(Statement : line 71, 'C++/lists.C' :type Return)
(Statement : line 74, 'C++/lists.C' :type While)
(Statement : line 74, 'C++/lists.C' :type Block)
(Statement : line 75, 'C++/lists.C' :type ExprStmt)
(Statement : line 76, 'C++/lists.C' :type ExprStmt)
(Statement : line 78, 'C++/lists.C' :type If)
(Statement : line 78, 'C++/lists.C' :type Block)
(Statement : line 79, 'C++/lists.C' :type ExprStmt)
(Statement : line 80, 'C++/lists.C' :type ExprStmt)
(Statement : line 81, 'C++/lists.C' :type ExprStmt)
(Statement : line 82, 'C++/lists.C' :type ExprStmt)
(Statement : line 84, 'C++/lists.C' :type If)
(Statement : line 84, 'C++/lists.C' :type Block)
(Statement : line 85, 'C++/lists.C' :type ExprStmt)
(Statement : line 86, 'C++/lists.C' :type ExprStmt)
(Statement : line 87, 'C++/lists.C' :type ExprStmt)
(Statement : line 88, 'C++/lists.C' :type ExprStmt)
(Statement : line 90, 'C++/lists.C' :type Block)
(Statement : line 91, 'C++/lists.C' :type ExprStmt)
(Statement : line 92, 'C++/lists.C' :type ExprStmt)
(Statement : line 93, 'C++/lists.C' :type ExprStmt)
(Statement : line 94, 'C++/lists.C' :type ExprStmt)
(Statement : line 96, 'C++/lists.C' :type ExprStmt)
(Statement : line 97, 'C++/lists.C' :type Return)
(EndFunctionNamed C++/lists.C)
(BeginFunctionNamed <<)
(Statement : line 119, 'C++/lists.C' :type For)
(Statement : line 120, 'C++/lists.C' :type ExprStmt)
(Statement : line 121, 'C++/lists.C' :type ExprStmt)
(Statement : line 122, 'C++/lists.C' :type Return)
(EndFunctionNamed C++/lists.C)
