(in-package #:phd-qcsp-alex)
(defun my-load ()
  (load "adt-template.lisp")
  (load "new-setup.lisp")
  (load "new-dep.lisp")
  (load "general-exp.lisp")
  (load "random-templ-exp.lisp")
  (load "static-order-exp.lisp")
  (load "cpu-xy.lisp") 
)

(defun my-compile ()
  (compile-file "adt-template.lisp")
  (compile-file "new-setup.lisp")
  (compile-file "new-dep.lisp")
  (compile-file "general-exp.lisp")
  (compile-file "random-templ-exp.lisp")
  (compile-file "static-order-exp.lisp")
  (compile-file "cpu-xy.lisp") 
)

(defun my-fasl ()
  (load "adt-template.fasl")
  (load "new-setup.fasl")
;  (load "new-dep.fasl")
  (load "2-pre.fasl")
;  (load "general-exp.fasl")
  (load "general-exp-2.fasl") 
  (load "random-templ-exp.fasl")
  (load "static-order-exp.fasl")
  (load "cpu-xy.fasl") 
)
