13 31
  1    1   31   17 X main
  2   -1    0    0 X socket
  3   -1    0    0 X perror
  4   -1    0    0 X gethostbyname
  5   -1    0    0 X exit
  6   -1    0    0 X memset
  7   -1    0    0 X sprintf
  8   -1    0    0 X inet_addr
  9   -1    0    0 X htons
 10   -1    0    0 X close
 11   -1    0    0 X connect
 12   -1    0    0 X send
 13   -1    0    0 X strlen
0 4 2
      74     200    1512 client.c
