globals 0 procs 11 addrs 4 chains 0 headers 0 files 1
  1    1   45   17 X main
  2   -1    0    0 X socket
  3   -1    0    0 X perror
  4   -1    0    0 X memset
  5   -1    0    0 X htons
  6   -1    0    0 X close
  7   -1    0    0 X bind
  8   -1    0    0 X listen
  9   -1    0    0 X accept
 10   -1    0    0 X printf
 11   -1    0    0 X recv

  0  11    45   58   1252 server.
