13 32
  1    1   32   16 X main
  2   -1    0    0 X socket
  3   -1    0    0 X perror
  4   -1    0    0 X gethostbyname
  5   -1    0    0 X exit
  6   -1    0    0 X memset
  7   -1    0    0 X fn1
  8   -1    0    0 X inet_addr
  9   -1    0    0 X htons
 10   -1    0    0 X close
 11   -1    0    0 X connect
 12   -1    0    0 X send
 13   -1    0    0 X strlen
0 0 2
      80     218    1616 clientorig.c
