;;************************************************************************************* 
;;load all templates except those will be generated by program
;;(load "adt-template.fasl")

;;
;; File set 1, with decomposed PreInc
;;
(setq *data-file-list-d*		
      '(
	("testdata/data-d/dmaxc.component" "testdata/data-d/dmaxc.control" "testdata/data-d/dmaxc.stats") 
	("testdata/data-d/dmax3c.component" "testdata/data-d/dmax3c.control" "testdata/data-d/dmax3c.stats")
	("testdata/data-d/dmax6c.component" "testdata/data-d/dmax6c.control" "testdata/data-d/dmax6c.stats")
	("testdata/data-d/dmax9c.component" "testdata/data-d/dmax9c.control" "testdata/data-d/dmax9c.stats")
	("testdata/data-d/dmax12c.component" "testdata/data-d/dmax12c.control" "testdata/data-d/dmax12c.stats")
	
	("testdata/data-d/dmax15c.component" "testdata/data-d/dmax15c.control" "testdata/data-d/dmax15c.stats")
	("testdata/data-d/dmax18c.component" "testdata/data-d/dmax18c.control" "testdata/data-d/dmax18c.stats")
	("testdata/data-d/dmax21c.component" "testdata/data-d/dmax21c.control" "testdata/data-d/dmax21c.stats")
	("testdata/data-d/dmax24c.component" "testdata/data-d/dmax24c.control" "testdata/data-d/dmax24c.stats")
	("testdata/data-d/dmax27c.component" "testdata/data-d/dmax27c.control" "testdata/data-d/dmax27c.stats")
	
	("testdata/data-d/dmax30c.component" "testdata/data-d/dmax30c.control" "testdata/data-d/dmax30c.stats")
	("testdata/data-d/dmax33c.component" "testdata/data-d/dmax33c.control" "testdata/data-d/dmax33c.stats")
	("testdata/data-d/dmax36c.component" "testdata/data-d/dmax36c.control" "testdata/data-d/dmax36c.stats")
	("testdata/data-d/dmax39c.component" "testdata/data-d/dmax39c.control" "testdata/data-d/dmax39c.stats")
	("testdata/data-d/dmax42c.component" "testdata/data-d/dmax42c.control" "testdata/data-d/dmax42c.stats")
	
	("testdata/data-d/dmax45c.component" "testdata/data-d/dmax45c.control" "testdata/data-d/dmax45c.stats")
	("testdata/data-d/dmax48c.component" "testdata/data-d/dmax48c.control" "testdata/data-d/dmax48c.stats")
	("testdata/data-d/dmax51c.component" "testdata/data-d/dmax51c.control" "testdata/data-d/dmax51c.stats")
	("testdata/data-d/dmax54c.component" "testdata/data-d/dmax54c.control" "testdata/data-d/dmax54c.stats")
;;added on April 29, 1997
	("testdata/data-d/dmax66c.component" "testdata/data-d/dmax66c.control" "testdata/data-d/dmax66c.stats")

	("testdata/data-d/dmax78c.component" "testdata/data-d/dmax78c.control" "testdata/data-d/dmax78c.stats")
	("testdata/data-d/dmax90c.component" "testdata/data-d/dmax90c.control" "testdata/data-d/dmax90c.stats")
	("testdata/data-d/dmax102c.component" "testdata/data-d/dmax102c.control" "testdata/data-d/dmax102c.stats")
	("testdata/data-d/dmax114c.component" "testdata/data-d/dmax114c.control" "testdata/data-d/dmax114c.stats")
	))


;;
;; File set 2, with PreInc
;;
(setq *data-file-list-c*		
      '(
	("testdata/data-c/dmaxc.component" "testdata/data-c/dmaxc.control" "testdata/data-c/dmaxc.stats") 
	("testdata/data-c/dmax3c.component" "testdata/data-c/dmax3c.control" "testdata/data-c/dmax3c.stats")
	("testdata/data-c/dmax6c.component" "testdata/data-c/dmax6c.control" "testdata/data-c/dmax6c.stats")
	("testdata/data-c/dmax9c.component" "testdata/data-c/dmax9c.control" "testdata/data-c/dmax9c.stats")
	("testdata/data-c/dmax12c.component" "testdata/data-c/dmax12c.control" "testdata/data-c/dmax12c.stats")
	
	("testdata/data-c/dmax15c.component" "testdata/data-c/dmax15c.control" "testdata/data-c/dmax15c.stats")
	("testdata/data-c/dmax18c.component" "testdata/data-c/dmax18c.control" "testdata/data-c/dmax18c.stats")
	("testdata/data-c/dmax21c.component" "testdata/data-c/dmax21c.control" "testdata/data-c/dmax21c.stats")
	("testdata/data-c/dmax24c.component" "testdata/data-c/dmax24c.control" "testdata/data-c/dmax24c.stats")
	("testdata/data-c/dmax27c.component" "testdata/data-c/dmax27c.control" "testdata/data-c/dmax27c.stats")
	
	("testdata/data-c/dmax30c.component" "testdata/data-c/dmax30c.control" "testdata/data-c/dmax30c.stats")
	("testdata/data-c/dmax33c.component" "testdata/data-c/dmax33c.control" "testdata/data-c/dmax33c.stats")
	("testdata/data-c/dmax36c.component" "testdata/data-c/dmax36c.control" "testdata/data-c/dmax36c.stats")
	("testdata/data-c/dmax39c.component" "testdata/data-c/dmax39c.control" "testdata/data-c/dmax39c.stats")
	("testdata/data-c/dmax42c.component" "testdata/data-c/dmax42c.control" "testdata/data-c/dmax42c.stats")
	
	("testdata/data-c/dmax45c.component" "testdata/data-c/dmax45c.control" "testdata/data-c/dmax45c.stats")
	("testdata/data-c/dmax48c.component" "testdata/data-c/dmax48c.control" "testdata/data-c/dmax48c.stats")
	("testdata/data-c/dmax51c.component" "testdata/data-c/dmax51c.control" "testdata/data-c/dmax51c.stats")
	("testdata/data-c/dmax54c.component" "testdata/data-c/dmax54c.control" "testdata/data-c/dmax54c.stats")
	("testdata/data-c/dmax66c.component" "testdata/data-c/dmax66c.control" "testdata/data-c/dmax66c.stats")

	("testdata/data-c/dmax78c.component" "testdata/data-c/dmax78c.control" "testdata/data-c/dmax78c.stats")
	("testdata/data-c/dmax90c.component" "testdata/data-c/dmax90c.control" "testdata/data-c/dmax90c.stats")
	("testdata/data-c/dmax102c.component" "testdata/data-c/dmax102c.control" "testdata/data-c/dmax102c.stats")
	("testdata/data-c/dmax114c.component" "testdata/data-c/dmax114c.control" "testdata/data-c/dmax114c.stats")
	)) 

;;************************************************************************************* 

;;
;;For experiment 7, static ordering
;;
(setq *template-list-7* '("traverse-array-template-5-7"))


(defun add-result-to-file-for-exp-other-than-static-ordering ( output-stream component-file )
  "
make a list of results we are interested in and append it to a file.
Those results are:
(0 plan-name)
(1 number-of-components-of-the-plan)
(2 number-of-constraints-of-the-plan)
(3 program-name)
(4 number-of-components-of-the-program)
(5 number-of-this-plan-related-components)
(6 ratio-of-5-over-4)
(7 average-domain-size)
;;(8 max-domain-size)
;;(9 min-domain-size)
(10 constaint-checks)
(11 successful-constraint-checks)
(12 failed-constraint-checks) 
(13 ratio-of-11-over-10)
(14 length-of-solution-set)
(15 cpu-search-time)
(16 *constraint-possible-data-dependency-cks*)
(17 *constraint-guaranteed-data-dependency-cks*)
(18 *constraint-same-data-dependency-cks*)
(19 *constraint-control-data-dependency-cks*)
(20 *constraint-same-variable-cks*)
(21 ratio of 15 over 10)
"
(let* ((r0 (nth 0 *current-template*))
       (r1 (length (nth 1 *current-template*)))
       (r2 (length (nth 2 *current-template*)))
       (r3 component-file)
       (r4 (length *current-situation*))
       (r5 (get-number-of-cur-plan-related-components))
       (r6 (coerce (/ r5 r4) 'float))
       (r7 *RECALL-avg-var-len*)
       (r10 *constraint-cks*)
       (r11 *constraint-success*)
       (r12 *constraint-failure*)
       (r13 (coerce (/ r11 r10) 'float))
       (r14 (length *solution-set*))
       (r15 *RECALL-search-time*)
;;following are added on December 26, 1996
       (r16 *constraint-possible-data-dependency-cks*)
       (r17 *constraint-guaranteed-data-dependency-cks*)
       (r18 *constraint-same-data-dependency-cks*)
       (r19 *constraint-control-data-dependency-cks*)
       (r20 *constraint-same-variable-cks*)
       (r21 (coerce (/ r15 r10) 'float))
       
       (r22 *node-consistency-checks*) 
       (r23 *node-type-consistency-checks*) 
       (r24 *node-type-consistency-ck-ok*) 
       (r25 *node-type-consistency-ck-fail*) 

       (r26 *dyn-rearr-cost*)
       (r27 *dfa-rearr-cost*)
       )
(format output-stream  "~a~%"
	(list r0 r1 r2 r3 r4 r5 r6 r7 r10 r11 r12 r13 r14 r15 r16 r17 r18 r19 r20 r21 r22 r23 r24 r25 r26 r27))))




(defun get-number-of-cur-plan-related-components ()
  (let ((affected-count 0)
	(type-list (mapcar #'first 
			   (get-type-set 
			    (mapcar #'caadr (nth 1 *current-template*))))))
    
    (setq *template-hash* (make-hash-table))
    (dolist (element type-list)
	    (setf (gethash element *template-hash*) 0))
    (dolist (element *current-situation*)
	    (let* ((this-node (second element))
		   (temp (gethash this-node *template-hash*)))
	      (if (not (null temp))  
		  (setf (gethash this-node *template-hash*) (+ temp 1)))))
    (dolist (element type-list)
	    (let ((tmp-cnt (gethash element *template-hash*)))
	      (if (not (null tmp-cnt))
		  (setq affected-count 
			(+  tmp-cnt affected-count)))))
  affected-count))
;;*************************************************************************************
;;
;;result is a list
(defun pick-two-for-xvgr (template-posi item-1 item-2 input-file output-file)

  (setq *my-result-xvgr*  (open output-file
				  :direction :output
				  :if-exists :overwrite
				  :if-does-not-exist :create))

  (with-open-file (in-stream input-file
			     :direction :input)
		  (let ((exp (read in-stream nil *end-of-file* nil)))
		    (dolist (t-elem exp)
			    (let* ((this-templ (nth template-posi t-elem))
				   (item1 (nth item-1 this-templ))
				   (item2 (nth item-2 this-templ)))
			     (format *my-result-xvgr* "~a ~a~%" item1 item2)))))
  
  (close *my-result-xvgr*)
)

;; three: cons-cks + type-consis-cks
(defun pick-three-for-xvgr (template-posi item-1 item-2 item-3 input-file output-file)

  (setq *my-result-xvgr*  (open output-file
				  :direction :output
				  :if-exists :overwrite
				  :if-does-not-exist :create))

  (with-open-file (in-stream input-file
			     :direction :input)
		  (let ((exp (read in-stream nil *end-of-file* nil)))
		    (dolist (t-elem exp)
			    (let* ((this-templ (nth template-posi t-elem))
				   (item1 (nth item-1 this-templ))
				   (item2 (nth item-2 this-templ))
				   (item3 (nth item-3 this-temp1)))
			     (format *my-result-xvgr* "~a ~a~%" item1 (+ item2 item3))))))
  
  (close *my-result-xvgr*)
)
;;************************************************************************************* 
;;
;; load dependency computation program
;;
;;(load "new-dep.fasl")



;;
;; General experiment program, input is the (data-file-list, template-list, print-template-option)
;; the template-list is just a list of template names that can be found in the global variable
;; *template-object-list*
;;
(defun experiment ( data-file-list template-list output-file &optional (print-template nil))
  (setq *my-result-stream*  (open output-file
				  :direction :output
				  :if-exists :overwrite
				  :if-does-not-exist :create))
  (format *my-result-stream* "~a~%" "(")
  (dolist (files-element data-file-list)
	  (progn
	    (format *my-result-stream* " ~a~%" "(")
;;	    (load "new-setup.fasl")
	    (format t
		    "~%Do files: ~a!"
		    files-element) 
	    (test-main (nth 0 files-element)
		       (nth 1 files-element)
		       (nth 2 files-element))
	    (dolist (template template-list)
		    (progn
		      (adt :template-id template
			   :forward-checking t
			   :dynamic-rearrangement t
			   :debug nil  
			   :debug-csp nil) 
;;			   :output-file "test-output-file")
		      (add-result-to-file-for-exp-other-than-static-ordering *my-result-stream* 
									     (nth 0 files-element))
		      
		      (if print-template 
			  (format t "~%Template ~a," 
				  (get-templ-object template))
			(format t "~%Template ~a," 
				(first (get-templ-object template))))	
		      (format t "~%Result length is ~a!~%"
			      (length *solution-set*))))
	    (format *my-result-stream* "~% ~a~%" ")")))
  (format *my-result-stream* "~%~a~%" ")")
  (close *my-result-stream*)
  )


;;************************************************************************************* 
;;
;;For experiment 1, test with a big plan "average-array-template-9-18", use decomposed
;;PreInc
(setq *template-list-1*	'("average-array-template-9-18" 
			;;  "increment-template-2-2"
			  ))
(defun experiment-1 ()  
  (experiment  *data-file-list-d* *template-list-1* "testdata/Results/exp-1-original-result" nil)
  )

;;*************************************************************************************
;;
;;For experiment 2, test with a big plan "average-array-template-8-14", use PreInc
;;
(setq *template-list-2* '("average-array-template-8-14")) 
(defun experiment-2 ()  
  (experiment  *data-file-list-c* *template-list-2* "testdata/Results/exp-2-original-result" nil)
  )

;;*************************************************************************************
;;
;;For experiment 3, test with Increment plan, decompose PreInc
;;
(setq *template-list-3* '("increment-template-2-2"))
(defun experiment-3 ()  
  (experiment  *data-file-list-d* *template-list-3* "testdata/Results/exp-3-original-result" nil)
  )

;;*************************************************************************************
;;
;;For experiment 4, remove some constraints from experiment 1 and experiment 2 manually
;;
(setq *template-list-4-1* '( 
			    "average-array-template-9-13"
			    "average-array-template-9-14"
			    "average-array-template-9-15"
			    "average-array-template-9-16"
			    "average-array-template-9-17"
			    "average-array-template-9-18"))
(setq *template-list-4-2* '(
			    "average-array-template-8-12"
			    "average-array-template-8-13"
			    "average-array-template-8-14")) 	


(defun experiment-4-1 ()  
  (experiment  *data-file-list-d* *template-list-4-1* "testdata/Results/exp-4-1-original-result" nil)
  )
(defun experiment-4-2 ()  
  (experiment  *data-file-list-c* *template-list-4-2* "testdata/Results/exp-4-2-original-result" nil)
  )

;;*************************************************************************************
;;
;;For experiment 5, function special-experiment, to test templates by randomly removing 
;;some constraints
;;
(defun experiment-5 ()
  (let ((data-file-list
	 '(("testdata/stats-c/dmax9c.component" 
	    "testdata/stats-c/dmax9c.control" 
	    "testdata/stats-c/dmax9c.stats"))) 
	(test-list (gen :how-many 5 :branch-factor 5)))
    (special-experiment data-file-list test-list))) 	

;;*************************************************************************************
;;
;;For experiment 6, a set of templates with increasing number of components,
;;use PreInc
(setq *template-list-6* '(
			  "reset-value-template-2-1"
;;			  "increment-template-2-2"
			  "copy-array-element-template-3-2"
			  "alloc-array-error-check-template-4-3"
			  "traverse-array-template-5-7"
			  "addup-array-template-6-9"
			  "copy-array-template-7-11"
			  "average-array-template-8-12"
			  "sum-square-array-9-16"
			  ))  
(defun experiment-6 ()  
  (experiment  *data-file-list-c* *template-list-6* "testdata/Results/exp-6-original-result" nil)
  )


;;*************************************************************************************
;;
;;For experiment 7, test static ordering,
;;use PreInc
;;
;; there is no difference between 7-1 and 7-2 because forward-checking doesn't work 
;;currently
;;
(defun experiment-7-1 ()
	(p-constraint-exp :data-file-list *data-file-list-c* 
			  :template-id "traverse-array-template-5-7"
			  :output-file "prefilter-static-5-7-result")  
)

(defun experiment-7-2 ()
	(p-constraint-exp :data-file-list *data-file-list-c*
			  :template-id "traverse-array-template-5-7"
			  :output-file "without-forward")  
)

;;************************************************************************************* 
;;
;;For experiment 8, test plans with one constraint (different for different plan, 
;;use decomposed PreInc
(setq *template-list-8*	'("guaranteed-data-dependency-2-1"
			  "possible-data-dependency-2-1"
			  "same-data-dependency-2-1"
			  "control-data-dependency-2-1"
			  "same-variable-2-1"))
(defun experiment-8 ()  
  (experiment  *data-file-list-d* *template-list-8* "testdata/Results/exp-8-original-result" nil)
  )

;;************************************************************************************* 
;;
;;Experiment 9, test one manual static ordering of the averate-array-template-8-14

(defun experiment-9 ()

  (static-cons-order-exp  
   *data-file-list-c* 
   (list (get-templ-object  "average-array-template-8-14-static-2")) 
  "testdata/Results/exp-9-initial-result-2" )
)

(defun exp-9-x-y ()
      (data-min-max-avg 
      "testdata/Results/exp-9-initial-result-1" 
	  "testdata/Results/exp-9-xx-yy"  
      "testdata/Results/Null1" 
      "testdata/Results/Null2")
) 

;;*************************************************************************************
;;
;;For experiment 10, test with a big plan "sample-variance-18-37", use PreInc
;;
(setq *template-list-10* '("sample-variance-18-37")) 
(defun experiment-10 ()  
  (experiment  *data-file-list-c* *template-list-10* "testdata/Results/exp-10-prefilter" nil)
  )
;;*************************************************************************************
 ;;
;;All experiments,
;;use PreInc
(defun all-experiments ()
(experiment-1)
(experiment-2)
(experiment-3)
;;(experiment-6)
;;  (experiment-4-1)
;;  (experiment-4-2)
;;(experiment-5)
)

;;*************************************************************************************
(defun get-all-xy () 
  (exp-1-xy)
  (exp-2-xy)
  (exp-3-xy)
;;  (exp-4-1-xy)
;;  (exp-4-2-xy)
;;  (exp-6-xy)
;;  (average-array-missed-in-exp-6-xy)
)
;;*************************************************************************************
(defun average-array-missed-in-exp-6-xy ()
  (pick-two-for-xvgr 0 
		     4 
		     8 
		     "testdata/Results/average-array-8-12-original-result" 
		     "testdata/Results/average-array-8-12-x-y")
)

(defun exp-1-xy ()
;;exp-1
  (pick-two-for-xvgr 0 
		     4 
		     8 
		     "testdata/Results/exp-1-prefilter-result" 
		     "testdata/Results/exp-1-prefilter-x-y")
)
(defun exp-2-xy ()
;;exp-2
  (pick-two-for-xvgr 0 
		     4 
		     8 
		     "testdata/Results/exp-2-prefilter-result" 
		     "testdata/Results/exp-2-prefilter-x-y")
)

(defun exp-3-xy ()
;;exp-3
  (pick-two-for-xvgr 0 
		     4 
		     8 
		     "testdata/Results/exp-3-prefilter-result" 
		     "testdata/Results/exp-3-prefilter-x-y")
)

(defun exp-6-xy ()
;;exp-6
  (pick-two-for-xvgr 0 
		     4 
		     8 
		     "testdata/Results/exp-6-prefilter-result" 
		     "testdata/Results/reset-value-prefilter-x-y")
  (pick-two-for-xvgr 1 
		     4 
		     8 
		     "testdata/Results/exp-6-prefilter-result" 
		     "testdata/Results/copy-array-element-prefilter-x-y")
  (pick-two-for-xvgr 2 
		     4 
		     8 
		     "testdata/Results/exp-6-prefilter-result" 
		     "testdata/Results/alloc-array-prefilter-x-y")
  (pick-two-for-xvgr 3 
		     4 
		     8 
		     "testdata/Results/exp-6-prefilter-result" 
		     "testdata/Results/traverse-array-prefilter-x-y")
  (pick-two-for-xvgr 4 
		     4 
		     8 
		     "testdata/Results/exp-6-prefilter-result" 
		     "testdata/Results/addup-array-prefilter-x-y")
  (pick-two-for-xvgr 5 
		     4 
		     8 
		     "testdata/Results/exp-6-prefilter-result" 
		     "testdata/Results/copy-array-prefilter-x-y")
  (pick-two-for-xvgr 6 
		     4 
		     8 
		     "testdata/Results/exp-6-prefilter-result" 
		     "testdata/Results/average-array-prefilter-x-y")

  (pick-two-for-xvgr 7 
		     4 
		     8 
		     "testdata/Results/exp-6-prefilter-result" 
		     "testdata/Results/sum-square-array-prefilter-x-y")
)

(defun exp-4-1-xy ()
;;exp-4-1
  (pick-two-for-xvgr 0 
		     4 
		     8 
		     "testdata/Results/exp-4-1-original-result" 
		     "testdata/Results/aa-9-13-x-y")
  (pick-two-for-xvgr 1 
		     4 
		     8 
		     "testdata/Results/exp-4-1-original-result" 
		     "testdata/Results/aa-9-14-x-y")
  (pick-two-for-xvgr 2 
		     4 
		     8 
		     "testdata/Results/exp-4-1-original-result" 
		     "testdata/Results/aa-9-15-x-y")
  (pick-two-for-xvgr 3 
		     4 
		     8 
		     "testdata/Results/exp-4-1-original-result" 
		     "testdata/Results/aa-9-16-x-y")
  (pick-two-for-xvgr 4 
		     4 
		     8 
		     "testdata/Results/exp-4-1-original-result" 
		     "testdata/Results/aa-9-17-x-y")
  (pick-two-for-xvgr 5 
		     4 
		     8 
		     "testdata/Results/exp-4-1-original-result" 
		     "testdata/Results/aa-9-18-x-y")

)

(defun exp-4-2-xy ()
;;exp-4-2
  (pick-two-for-xvgr 0 
		     4 
		     8 
		     "testdata/Results/exp-4-2-original-result" 
		     "testdata/Results/aa-8-12-x-y")
  (pick-two-for-xvgr 1 
		     4 
		     8 
		     "testdata/Results/exp-4-2-original-result" 
		     "testdata/Results/aa-8-13-x-y")
  (pick-two-for-xvgr 2 
		     4 
		     8 
		     "testdata/Results/exp-4-2-original-result" 
		     "testdata/Results/aa-8-14-x-y")

)


;;*************************************************************************************
(defun abnormaly ()
  (let ((data-file-list
	 '(
       ("testdata/data-c/dmax6c.component" 
	    "testdata/data-c/dmax6c.control" 
	    "testdata/data-c/dmax6c.stats")
       ("testdata/data-c/dmax7c.component" 
	    "testdata/data-c/dmax7c.control" 
	    "testdata/data-c/dmax7c.stats")
       ("testdata/data-c/dmax8c.component" 
	    "testdata/data-c/dmax8c.control" 
	    "testdata/data-c/dmax8c.stats")
	   ("testdata/data-c/dmax9c.component" 
	    "testdata/data-c/dmax9c.control" 
	    "testdata/data-c/dmax9c.stats")
	   ("testdata/data-c/dmax10c.component" 
	    "testdata/data-c/dmax10c.control" 
	    "testdata/data-c/dmax10c.stats")
	   ("testdata/data-c/dmax11c.component" 
	    "testdata/data-c/dmax11c.control" 
	    "testdata/data-c/dmax11c.stats")
	   ("testdata/data-c/dmax12c.component" 
	    "testdata/data-c/dmax12c.control" 
	    "testdata/data-c/dmax12c.stats"))))
    (experiment data-file-list '("sum-square-array-9-16"))))

(defun explore-9 ()
  (let ((data-file-list
	 '(("testdata/data-c/dmax9c.component" 
	    "testdata/data-c/dmax9c.control" 
	    "testdata/data-c/dmax9c.stats"))) 
	(test-list (gen :how-many 5 :branch-factor 5)))
    (special-experiment data-file-list test-list))) 	

(defun all-exp-4 ()
  (let ((data-file-list
	 '(("testdata/data-c/dmax3c.component" 
	    "testdata/data-c/dmax3c.control" 
	    "testdata/data-c/dmax3c.stats")))) 
    (experiment data-file-list '("sum-square-array-9-16"))))

;;************************************************************************************* 









