

;;
;;test templates that are generated by randomly removing constraints from one template, these
;;templates are like ( (original-template) (level-1-templates) (level-2-templates) ..) 
;;level-n means n constraints are removed from the original, we call it random-template-tree
;;Input is the (data-file-list template-body-list-list), the second parameter is as described
;;above, the real template body are in this parameter rather than just the template name
;;
(defun special-experiment ( data-file-list template-body-list-list )
;;explore random template tree 
  (dolist (files-element data-file-list)
	  (progn
	    (load "new-setup.fasl")
	    (format t
		    "~%Do files: ~a!"
		    files-element) 
	    (test-main (nth 0 files-element)
		       (nth 1 files-element)
		       (nth 2 files-element))
	    (let ((count 0)
		  (ave-constr 0)
		  (temp-cnt 0)) 
	      (dolist (template-body-list template-body-list-list)
		      (progn 
			(setq ave-constr 0) 
			(setq temp-cnt 0) 
			(dolist (template template-body-list)
				(progn
				  (adt :template-id "special" 
				       :forward-checking t
				       :dynamic-rearrangement t 
				       :override-template template)
				  (format 
				   t
				   "Level ~a Number ~a Template ~a,~%Result length is ~a!~%"
				   count
				   temp-cnt 
				   template 
				   (length *solution-set*))
				  (setq temp-cnt (+ temp-cnt 1)) 
				  (setq ave-constr 
					(+ ave-constr 
					   (+ *constraint-success* 
					      *constraint-failure*)))))	
			
			(format t
				"Level ~a, average constraint checks is ~a!~%~%"
				count
				(coerce (/ ave-constr (length template-body-list)) 
					'float))    
			(setq count (+ count 1)))			
		      )))))


;;************************************************************************************* 
;; Functions to generate template tree  
(defun remove-item (alist which-one)
  (cond ((endp alist) nil)
	((eq which-one 0) (rest alist))
	(T (cons (first alist) 
		 (remove-item (rest alist) (- which-one 1)))))
  )

(defun get-affected-components ( constraint-list )  
  (cond ((endp constraint-list) nil)
	(T (append (second (first constraint-list)) 
		   (get-affected-components (rest constraint-list)))))
  )

(defun pick-random (template-list how-many &optional (temp nil))
  (cond ((null template-list) temp) 
	((eq how-many 0) temp)
	(T
	 (let ((to-remove (random (length template-list))))  
	   (pick-random (remove-item template-list to-remove)
			(- how-many 1)
			(cons (nth to-remove template-list)
			      temp)))))   
  )

;;
;;if any component is not constrainted, remove it
;;
(defun stablize-template ( template )
  (let*
      ((affected-components (get-affected-components (third template)))
       (components 
	(remove-if #'(lambda (x)
		       (not (member (first x) affected-components)))
		   (second template))))
    (list
     (format nil "test-~a-~a" (length components) 
	     (length (third template))) 
     components 	
     (third template)))  	
  )

;;
;;remove a certain constraint, use its position in the constraint list
;;
(defun remove-one-constraint (template constraint-num )
  (stablize-template 
   (list (first template)
	 (second template)
	 (remove-item (third template) constraint-num) ) 
   ) 
  )

;;
;;generate a set of constraints by removing each of the constraint,
;;the generated set has a length of the number of constraints
;;
(defun generate-one-set (template) 
  (let* ((result nil)
	 (all-constraints (third template)) 
	 (cnumber (length all-constraints)))
    (dotimes (count cnumber result)
	     (setf result (cons (remove-one-constraint template count)	
				result))))  	
  )

;;
;;generate a set of all possible templates from a list of templates
;;expected number of templates will be picked from this set randomly
;;
(defun generate-set (original-template-list &optional (temp nil)) 
  (cond ((endp original-template-list) temp)
	(T 
	 (generate-set (rest original-template-list) 
		       (append temp (generate-one-set 
				     (first original-template-list))))))  
  ) 

;;
;;to generate the random-template-tree with given depth and branch factor
;;depth means the level we mentioned above, branch factor is how many times of
;;templates to generate in a child level than in its parent level 
;;
(defun generate-random-templates ( original-template-list depth branch-factor)
  (let* ((result (list original-template-list))
	 (temp-result (generate-set original-template-list)))
    (dotimes (count depth result)
	     (progn 
	       (setf temp-result    
		     (pick-random temp-result (* (+ 1 count) branch-factor)))
	       (cond ((not (null temp-result)) 
		      (setf result (append result (list temp-result)))))  
	       (setf temp-result (generate-set temp-result)))) 
    )	
  )

;;
;;to cound how many templates that have been genrated
;;
(defun total-number ( result )
  (cond ((endp result) 0)
	(T (+ (length (first result))
	      (total-number (rest result))))) 
  )

;;************************************************************************************* 
;;main function to call to generate random-template-tree, put default
;;
(defun gen ( &key
	     (template-id "sum-square-array-9-16")
	     (how-many 3)
	     (branch-factor 3))
  (let ((result  
	 (generate-random-templates (list (get-templ-object template-id)) 
				    how-many 
				    branch-factor))) 
    (format t
	    "~%Total generated templates: ~a"
	    (total-number result))
    result)) 

;;************************************************************************************* 
(load "static-order-exp.fasl")
;;************************************************************************************* 




